{% set name = "semantic-code-search" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semantic-code-search-{{ version }}.tar.gz
  sha256: edfcbe631a09f0f981cab0fd9863e8d0a2ec78d5f6b9f4c168b087cd9836c218

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - sem=semantic_code_search.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy ==1.22.4
    - prompt-toolkit ==3.0.32
    - pygments ==2.12.0
    - sentence-transformers ==2.2.2
    - setuptools ==62.6.0
    - pytorch ==1.12.1
    - tokenizers >=0.11.1,!=0.11.3,<0.13
    - tree_sitter ==0.20.1
    - tree_sitter_languages ==1.5.0

test:
  imports:
    - semantic_code_search
  commands:
    - git init
    - sem --help
  requires:
    - git
    - python {{ python_min }}

about:
  home: https://github.com/sturdy-dev/semantic-code-search
  summary: Search your codebase with natural language.
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
